CREATE TABLE `billing_retention_records` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`uid` text NOT NULL,
	`provider` text NOT NULL,
	`provider_event_id` text,
	`billing_event_id` integer,
	`event_type` text NOT NULL,
	`event_occurred_at` integer NOT NULL,
	`workspace_id_snapshot` integer,
	`workspace_uid_snapshot` text,
	`workspace_name_snapshot` text,
	`billing_owner_user_id_snapshot` integer,
	`plan_code` text DEFAULT 'BASIC' NOT NULL,
	`product_code` text,
	`billing_interval` text,
	`seat_count` integer,
	`unit_price` integer,
	`currency` text,
	`amount` integer,
	`tax_amount` integer,
	`tax_rate` text,
	`tax_jurisdiction` text,
	`customer_key` text,
	`subscription_key` text,
	`checkout_id` text,
	`order_id` text,
	`invoice_id` text,
	`payment_id` text,
	`receipt_url` text,
	`current_period_start` integer,
	`current_period_end` integer,
	`paid_at` integer,
	`refunded_at` integer,
	`canceled_at` integer,
	`terms_version` text,
	`privacy_policy_version` text,
	`billing_policy_version` text,
	`checkout_notice_version` text,
	`auto_renewal_notice_accepted_at` integer,
	`ip_country` text,
	`billing_country` text,
	`tax_evidence_source` text,
	`normalized_payload_json` text NOT NULL,
	`legal_retention_until` integer NOT NULL,
	`legal_hold` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	FOREIGN KEY (`billing_event_id`) REFERENCES `billing_events`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `billing_retention_records_uid_unique` ON `billing_retention_records` (`uid`);--> statement-breakpoint
CREATE UNIQUE INDEX `billing_retention_records_provider_event_unique` ON `billing_retention_records` (`provider`,`provider_event_id`,`event_type`);--> statement-breakpoint
CREATE INDEX `billing_retention_records_workspace_idx` ON `billing_retention_records` (`workspace_id_snapshot`);--> statement-breakpoint
CREATE INDEX `billing_retention_records_retention_until_idx` ON `billing_retention_records` (`legal_retention_until`);