import { getLocale, type Locale } from "@/lib/server/locale";
import { NextResponse } from "next/server";
import ko from "@/messages/ko.json";
import en from "@/messages/en.json";

export type ErrorCode =
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "TEST_ACCOUNT_WRITE_RESTRICTED"
  | "NOT_FOUND"
  | "VALIDATION_ERROR"
  | "INTERNAL_ERROR"
  | "INVALID_CREDENTIALS"
  | "LOGIN_RATE_LIMITED"
  | "INVALID_RECOVERY_CODE"
  | "SESSION_EXPIRED"
  | "WRONG_PASSWORD"
  | "LAST_ADMIN_ACCOUNT_DELETION_FORBIDDEN"
  | "INVALID_INVITE_CODE"
  | "EXPIRED_INVITE_CODE"
  | "INVITE_CODE_INACTIVE"
  | "INVITE_CODE_USAGE_LIMIT_REACHED"
  | "BETA_PROMOTION_CODE_INACTIVE"
  | "BETA_PROMOTION_CODE_USAGE_LIMIT_REACHED"
  | "BETA_PROMOTION_CODE_ALREADY_USED"
  | "BETA_PROMOTION_CODE_ALREADY_EXISTS"
  | "CUSTOM_ID_ALREADY_EXISTS"
  | "ALREADY_IN_WORKSPACE"
  | "WORKSPACE_PAYMENT_REQUIRED"
  | "WORKSPACE_CHECKOUT_ALREADY_PENDING"
  | "WORKSPACE_CHECKOUT_NOT_READY"
  | "WORKSPACE_CHECKOUT_OWNER_MISMATCH"
  | "WORKSPACE_MEMBER_LIMIT_REACHED"
  | "WORKSPACE_SEAT_LIMIT_EXCEEDED"
  | "BASIC_SUBSCRIPTION_REQUIRED"
  | "WORKSPACE_TAG_ALREADY_EXISTS"
  | "ADMIN_TRANSFER_REQUIRED"
  | "CANNOT_REMOVE_LAST_ADMIN"
  | "ACTIVE_SCOREBOARD_EXISTS"
  | "SCOREBOARD_ALREADY_ACTIVE"
  | "SCOREBOARD_ARCHIVED"
  | "LEAD_MEASURE_ALREADY_ACTIVE"
  | "LEAD_MEASURE_ALREADY_ARCHIVED"
  | "LEAD_MEASURE_ARCHIVED"
  | "FUTURE_DATE_NOT_ALLOWED"
  | "PAST_WEEK_LOG_EDIT_NOT_ALLOWED"
  | "BILLING_NOT_READY"
  | "BILLING_SEAT_COUNT_BELOW_MEMBER_COUNT"
  | "BILLING_REVIEW_REQUIRED";

const ERROR_MESSAGES: Record<Locale, Record<ErrorCode, string>> = {
  ko: ko.ApiError as Record<ErrorCode, string>,
  en: en.ApiError as Record<ErrorCode, string>,
};

const ERROR_STATUS: Partial<Record<ErrorCode, number>> = {
  UNAUTHORIZED: 401,
  SESSION_EXPIRED: 401,
  INVALID_CREDENTIALS: 401,
  LOGIN_RATE_LIMITED: 429,
  INVALID_RECOVERY_CODE: 404,
  WRONG_PASSWORD: 400,
  LAST_ADMIN_ACCOUNT_DELETION_FORBIDDEN: 403,
  FUTURE_DATE_NOT_ALLOWED: 400,
  PAST_WEEK_LOG_EDIT_NOT_ALLOWED: 403,
  SCOREBOARD_ALREADY_ACTIVE: 400,
  LEAD_MEASURE_ALREADY_ACTIVE: 400,
  LEAD_MEASURE_ALREADY_ARCHIVED: 400,
  FORBIDDEN: 403,
  TEST_ACCOUNT_WRITE_RESTRICTED: 403,
  CANNOT_REMOVE_LAST_ADMIN: 403,
  SCOREBOARD_ARCHIVED: 403,
  LEAD_MEASURE_ARCHIVED: 403,
  NOT_FOUND: 404,
  INVALID_INVITE_CODE: 404,
  EXPIRED_INVITE_CODE: 410,
  INVITE_CODE_INACTIVE: 409,
  INVITE_CODE_USAGE_LIMIT_REACHED: 409,
  BETA_PROMOTION_CODE_INACTIVE: 409,
  BETA_PROMOTION_CODE_USAGE_LIMIT_REACHED: 409,
  BETA_PROMOTION_CODE_ALREADY_USED: 409,
  BETA_PROMOTION_CODE_ALREADY_EXISTS: 409,
  CUSTOM_ID_ALREADY_EXISTS: 409,
  ALREADY_IN_WORKSPACE: 409,
  WORKSPACE_PAYMENT_REQUIRED: 409,
  WORKSPACE_CHECKOUT_ALREADY_PENDING: 409,
  WORKSPACE_CHECKOUT_NOT_READY: 409,
  WORKSPACE_CHECKOUT_OWNER_MISMATCH: 403,
  WORKSPACE_MEMBER_LIMIT_REACHED: 409,
  WORKSPACE_SEAT_LIMIT_EXCEEDED: 403,
  BASIC_SUBSCRIPTION_REQUIRED: 403,
  WORKSPACE_TAG_ALREADY_EXISTS: 409,
  ADMIN_TRANSFER_REQUIRED: 409,
  ACTIVE_SCOREBOARD_EXISTS: 409,
  BILLING_NOT_READY: 409,
  BILLING_SEAT_COUNT_BELOW_MEMBER_COUNT: 409,
  BILLING_REVIEW_REQUIRED: 409,
  VALIDATION_ERROR: 422,
  INTERNAL_ERROR: 500,
};

export const apiError = async (code: ErrorCode, details?: unknown) => {
  const locale = await getLocale();
  const status = ERROR_STATUS[code] ?? 400;
  return NextResponse.json(
    {
      error: {
        code,
        message: ERROR_MESSAGES[locale][code],
        ...(details ? { details } : {}),
      },
    },
    { status },
  );
};

export const apiSuccess = <T>(data: T, status = 200) => {
  if (status === 204) {
    return new NextResponse(null, { status });
  }
  return NextResponse.json(data, { status });
};
