export const SESSION_TTL_SECONDS = 60 * 60 * 24 * 30;
export const SESSION_TTL_MS = SESSION_TTL_SECONDS * 1000;
export const SESSION_REISSUE_INTERVAL_SECONDS = 60 * 60 * 24 * 3;
export const SESSION_REISSUE_INTERVAL_MS = SESSION_REISSUE_INTERVAL_SECONDS * 1000;
